"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { signInWithGoogle } from "../lib/firebase";

function GoogleIcon(){return <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg>}

type Stats = Record<"users"|"active_users"|"households"|"transactions"|"transactions_30d"|"active_wallets"|"requests_24h", number>;
type User = {id:string;name:string|null;email:string;is_active:boolean;email_verified_at:string|null;created_at:string;deactivated_reason:string|null};

export default function Home() {
  const [authenticated,setAuthenticated]=useState<boolean|null>(null), [stats,setStats]=useState<Stats|null>(null);
  const [users,setUsers]=useState<User[]>([]), [view,setView]=useState<"dashboard"|"users">("dashboard"), [error,setError]=useState("");
  const [googleLoading,setGoogleLoading]=useState(false);
  const load=useCallback(async()=>{const r=await fetch("/api/dashboard",{credentials:"include",cache:"no-store"});if(r.status===401){setAuthenticated(false);return}if(!r.ok)throw new Error("Dashboard gagal dimuat");setStats(await r.json());setAuthenticated(true)},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const form=new FormData(e.currentTarget);const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});if(!r.ok){setError("E-mel atau kata laluan tidak sah");return}await load()}
  async function loginGoogle(){setError("");setGoogleLoading(true);try{const idToken=await signInWithGoogle();const r=await fetch("/api/auth/google",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id_token:idToken})});if(!r.ok){const d=await r.json().catch(()=>null);setError((d&&d.detail)||"Akaun Google ini bukan pentadbir");return}await load()}finally{setGoogleLoading(false)}}
  async function showUsers(q=""){setView("users");const r=await fetch(`/api/users?q=${encodeURIComponent(q)}`,{credentials:"include"});if(!r.ok){setError("Senarai pengguna gagal dimuat");return}setUsers(await r.json())}
  if(authenticated===null)return <main className="login"><p className="muted">Memuatkan Mastermind…</p></main>;
  if(!authenticated)return <main className="login"><form className="card" onSubmit={login}><h1>Mastermind</h1><p className="muted">Portal pentadbiran MyPeribadi</p><button type="button" className="primary google" onClick={()=>void loginGoogle()} disabled={googleLoading}><GoogleIcon/><span>{googleLoading?"Memproses…":"Log masuk dengan Google"}</span></button><div className="divider"><span>atau</span></div><div className="label">Log masuk dengan e-mel</div><input className="field" name="email" type="email" placeholder="E-mel admin" required autoComplete="username"/><input className="field" name="password" type="password" placeholder="Kata laluan" required autoComplete="current-password"/><button className="primary">Log masuk</button>{error&&<p className="error">{error}</p>}</form></main>;
  const cards: [string,number|undefined][]=[["Jumlah pengguna",stats?.users],["Pengguna aktif",stats?.active_users],["Household",stats?.households],["Transaksi",stats?.transactions],["Transaksi 30 hari",stats?.transactions_30d],["Wallet aktif",stats?.active_wallets],["Permintaan 24 jam",stats?.requests_24h]];
  return <div className="shell"><aside className="side"><div className="brand">Mastermind</div><small>MyPeribadi Admin</small><nav className="nav"><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>Dashboard</button><button className={view==="users"?"active":""} onClick={()=>void showUsers()}>Pengguna</button></nav></aside><main className="main"><header className="top"><div><h1>{view==="dashboard"?"Ringkasan sistem":"Pengguna"}</h1><p className="muted">Akses pentadbiran berasingan, baca sahaja.</p></div><button className="primary" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});setAuthenticated(false)}}>Log keluar</button></header>{error&&<p className="error">{error}</p>}{view==="dashboard"?<section className="grid">{cards.map(([label,value])=><article className="card" key={label}><span className="muted">{label}</span><div className="metric">{value?.toLocaleString("ms-MY")??"—"}</div></article>)}</section>:<section className="card"><input className="search" placeholder="Cari nama atau e-mel" onChange={e=>void showUsers(e.target.value)}/><table className="table"><thead><tr><th>Pengguna</th><th>Status</th><th>Verified</th><th>Daftar</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name||"—"}</strong><br/><span className="muted">{u.email}</span></td><td>{u.is_active?"Aktif":u.deactivated_reason||"Tidak aktif"}</td><td>{u.email_verified_at?"Ya":"Tidak"}</td><td>{new Date(u.created_at).toLocaleDateString("ms-MY")}</td></tr>)}</tbody></table></section>}</main></div>;
}
