"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Stats = Record<"users"|"active_users"|"households"|"transactions"|"transactions_30d"|"active_wallets"|"requests_24h", number>;
type User = {id:string;name:string|null;email:string;is_active:boolean;email_verified_at:string|null;created_at:string;deactivated_reason:string|null};

export default function Home() {
  const [authenticated,setAuthenticated]=useState<boolean|null>(null), [stats,setStats]=useState<Stats|null>(null);
  const [users,setUsers]=useState<User[]>([]), [view,setView]=useState<"dashboard"|"users">("dashboard"), [error,setError]=useState("");
  const load=useCallback(async()=>{const r=await fetch("/api/dashboard",{credentials:"include",cache:"no-store"});if(r.status===401){setAuthenticated(false);return}if(!r.ok)throw new Error("Dashboard gagal dimuat");setStats(await r.json());setAuthenticated(true)},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const form=new FormData(e.currentTarget);const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});if(!r.ok){setError("E-mel atau kata laluan tidak sah");return}await load()}
  async function showUsers(q=""){setView("users");const r=await fetch(`/api/users?q=${encodeURIComponent(q)}`,{credentials:"include"});if(!r.ok){setError("Senarai pengguna gagal dimuat");return}setUsers(await r.json())}
  if(authenticated===null)return <main className="login"><p className="muted">Memuatkan Mastermind…</p></main>;
  if(!authenticated)return <main className="login"><form className="card" onSubmit={login}><h1>Mastermind</h1><p className="muted">Portal pentadbiran MyPeribadi</p><input className="field" name="email" type="email" placeholder="E-mel admin" required autoComplete="username"/><input className="field" name="password" type="password" placeholder="Kata laluan" required autoComplete="current-password"/><button className="primary">Log masuk</button>{error&&<p className="error">{error}</p>}</form></main>;
  const cards: [string,number|undefined][]=[["Jumlah pengguna",stats?.users],["Pengguna aktif",stats?.active_users],["Household",stats?.households],["Transaksi",stats?.transactions],["Transaksi 30 hari",stats?.transactions_30d],["Wallet aktif",stats?.active_wallets],["Permintaan 24 jam",stats?.requests_24h]];
  return <div className="shell"><aside className="side"><div className="brand">Mastermind</div><small>MyPeribadi Admin</small><nav className="nav"><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>Dashboard</button><button className={view==="users"?"active":""} onClick={()=>void showUsers()}>Pengguna</button></nav></aside><main className="main"><header className="top"><div><h1>{view==="dashboard"?"Ringkasan sistem":"Pengguna"}</h1><p className="muted">Akses pentadbiran berasingan, baca sahaja.</p></div><button className="primary" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});setAuthenticated(false)}}>Log keluar</button></header>{error&&<p className="error">{error}</p>}{view==="dashboard"?<section className="grid">{cards.map(([label,value])=><article className="card" key={label}><span className="muted">{label}</span><div className="metric">{value?.toLocaleString("ms-MY")??"—"}</div></article>)}</section>:<section className="card"><input className="search" placeholder="Cari nama atau e-mel" onChange={e=>void showUsers(e.target.value)}/><table className="table"><thead><tr><th>Pengguna</th><th>Status</th><th>Verified</th><th>Daftar</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name||"—"}</strong><br/><span className="muted">{u.email}</span></td><td>{u.is_active?"Aktif":u.deactivated_reason||"Tidak aktif"}</td><td>{u.email_verified_at?"Ya":"Tidak"}</td><td>{new Date(u.created_at).toLocaleDateString("ms-MY")}</td></tr>)}</tbody></table></section>}</main></div>;
}
